---
swagger: "2.0"
info:
  description: ACR Connect component exposing APIs to upload files/data to ACR Cloud.
  version: 1.0.0
  title: Upload Manager API
host: virtserver.swaggerhub.com
basePath: /ACRTest/UploadManager/1.0.0
schemes:
- https
paths:
  /api/internalUserAccessToken:
    post:
      tags:
      - Auth
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: token
        in: formData
        required: false
        type: string
      responses:
        "200":
          description: Success
  /api/upload-task:
    post:
      tags:
      - UploadTask
      summary: "Creates a new task to upload given files.\r\nFinally enqueus the task to processing queue for background work."
      operationId: Upload:SubmitTask
      consumes:
      - application/json
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - in: body
        name: body
        required: false
        schema:
          $ref: '#/definitions/UploadTask'
      responses:
        "204":
          description: Success
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResource'
definitions:
  UploadTaskItem:
    type: object
    required:
    - filePath
    properties:
      id:
        type: string
        format: uuid
      filePath:
        type: string
  UploadTask:
    type: object
    required:
    - callBackUrl
    - id
    properties:
      id:
        type: string
        format: uuid
      callBackUrl:
        type: string
        format: uri
      items:
        type: array
        items:
          $ref: '#/definitions/UploadTaskItem'
      metaData:
        type: string
  ErrorDetails:
    type: object
    properties:
      code:
        type: string
        readOnly: true
      message:
        type: string
        readOnly: true
      target:
        type: string
        readOnly: true
      details:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/ErrorDetails'
  ErrorResource:
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDetails'
